// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG19_DJfW85x8dTqpGMwREAB3Q86vbIAM',
    appId: '1:362659280973:web:f6600654dcbf58ef954404',
    messagingSenderId: '362659280973',
    projectId: 'studymate-724d9',
    authDomain: 'studymate-724d9.firebaseapp.com',
    storageBucket: 'studymate-724d9.firebasestorage.app',
    measurementId: 'G-Z54E087ZTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJuapkjMT-hGAjx3IMQ3N8eJw2sH45EFE',
    appId: '1:362659280973:android:dcc031c86a111f2b954404',
    messagingSenderId: '362659280973',
    projectId: 'studymate-724d9',
    storageBucket: 'studymate-724d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYNjQA2nvMCsYBm9KgNsoTMvCWyeToTfA',
    appId: '1:362659280973:ios:ef17704f04ed0eaa954404',
    messagingSenderId: '362659280973',
    projectId: 'studymate-724d9',
    storageBucket: 'studymate-724d9.firebasestorage.app',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYNjQA2nvMCsYBm9KgNsoTMvCWyeToTfA',
    appId: '1:362659280973:ios:ef17704f04ed0eaa954404',
    messagingSenderId: '362659280973',
    projectId: 'studymate-724d9',
    storageBucket: 'studymate-724d9.firebasestorage.app',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG19_DJfW85x8dTqpGMwREAB3Q86vbIAM',
    appId: '1:362659280973:web:7a37a0260593c776954404',
    messagingSenderId: '362659280973',
    projectId: 'studymate-724d9',
    authDomain: 'studymate-724d9.firebaseapp.com',
    storageBucket: 'studymate-724d9.firebasestorage.app',
    measurementId: 'G-WYBV36GXCH',
  );
}
